# Generated by Django 5.1.8 on 2026-08-04 00:53

import archives.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0013_classroom_moyenne_min_admission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YearClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=9, unique=True)),
                ('status', models.CharField(choices=[('PREPARING', 'Préparation'), ('REFRESHING', 'Mise à jour des archives'), ('ARCHIVED', 'Archives à jour'), ('CLEANED', 'Nettoyé'), ('CLOSED', 'Clôturé')], default='PREPARING', max_length=12)),
                ('selected_types', models.JSONField(blank=True, default=list)),
                ('steps', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('classrooms', models.PositiveSmallIntegerField(default=0)),
                ('students', models.PositiveSmallIntegerField(default=0)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closures_finished', to=settings.AUTH_USER_MODEL)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closures_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'YearClosure',
                'ordering': ['-school_year'],
            },
        ),
        migrations.CreateModel(
            name='ArchivedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(db_index=True, max_length=9)),
                ('doc_type', models.CharField(choices=[('BULLETIN', 'Bulletins scolaires'), ('BULLETIN_WITH_COMPETENCES', 'Bulletins avec compétences'), ('PV', 'Procès verbaux'), ('CLASS_LIST', 'Listes de classe'), ('ALBUM', 'Albums photos de classe'), ('STATS_AGE_SEXE', 'Statistiques (âge / sexe)'), ('STATS_REUSSITE', 'Statistiques de réussite'), ('CLOSURE_REPORT', 'Rapport de clôture')], db_index=True, max_length=30)),
                ('classroom_label', models.CharField(blank=True, default='', max_length=30)),
                ('effectif', models.PositiveSmallIntegerField(default=0)),
                ('term_index', models.SmallIntegerField(blank=True, null=True)),
                ('unit_key', models.CharField(default='', editable=False, max_length=120, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('file', models.FileField(blank=True, null=True, upload_to=archives.models.archive_upload_path)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('page_count', models.PositiveSmallIntegerField(default=0)),
                ('page_map', models.JSONField(blank=True, null=True)),
                ('params', models.JSONField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('versions', models.PositiveSmallIntegerField(default=1)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_documents', to='classroom.classroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ArchivedDocument',
                'ordering': ['school_year', 'doc_type', 'classroom_label', 'term_index'],
                'indexes': [models.Index(fields=['school_year', 'doc_type'], name='ArchivedDoc_school__fa00a4_idx'), models.Index(fields=['school_year', 'doc_type', 'classroom', 'term_index'], name='ArchivedDoc_school__2c9bc0_idx')],
            },
        ),
    ]
