# Generated by Django 5.1.8 on 2026-08-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveddocument',
            name='old_archive',
            field=models.BooleanField(default=False),
        ),
    ]
