# Generated by Django 5.1.8 on 2026-08-12 03:48

import archives.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_archiveddocument_old_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveddocument',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=archives.models.archive_upload_path),
        ),
    ]
