# Generated by Django 5.1.8 on 2026-09-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_alter_archiveddocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveddocument',
            name='doc_type',
            field=models.CharField(choices=[('BULLETIN', 'Bulletins scolaires'), ('BULLETIN_WITH_COMPETENCES', 'Bulletins avec compétences'), ('PV', 'Procès verbaux'), ('CLASS_LIST', 'Listes de classe'), ('ALBUM', 'Albums photos de classe'), ('STATS_AGE_SEXE', 'Statistiques (âge / sexe)'), ('TRANSFER_LIST', 'Liste des transferts'), ('STATS_REUSSITE', 'Statistiques de réussite'), ('CLOSURE_REPORT', 'Rapport de clôture')], db_index=True, max_length=30),
        ),
    ]
