# Generated by Django 5.1.8 on 2026-07-12 16:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0013_alter_personnel_options_alter_personnel_managers_and_more'),
        ('student', '0011_alter_studentenrollment_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.IntegerField(default=0, help_text="Fonds existants à l'adoption de la plateforme")),
                ('opening_date', models.DateField(default=django.utils.timezone.localdate)),
            ],
            options={
                'db_table': '"CashBox"',
            },
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, unique=True)),
                ('affects_cashbox', models.BooleanField(default=True, help_text="Décocher pour les fonds collectés puis reversés à l'État (frais exigibles, frais d'examen) : suivis mais hors caisse.")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"FeeType"',
            },
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, unique=True)),
                ('kind', models.CharField(choices=[('RECETTE', 'Recette'), ('DEPENSE', 'Dépense')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"TransactionCategory"',
            },
        ),
        migrations.CreateModel(
            name='SchoolFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(db_index=True, max_length=9)),
                ('level', models.CharField(blank=True, help_text='Vide = tous les niveaux', max_length=15, null=True)),
                ('serie', models.CharField(blank=True, help_text='Vide = toutes les séries du niveau', max_length=10, null=True)),
                ('amount', models.PositiveIntegerField(help_text='Montant total (FCFA)')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='finance.feetype')),
            ],
            options={
                'db_table': '"SchoolFee"',
                'unique_together': {('fee_type', 'school_year', 'level', 'serie')},
            },
        ),
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('amount', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('school_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance.schoolfee')),
            ],
            options={
                'db_table': '"FeeInstallment"',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('RECETTE', 'Recette'), ('DEPENSE', 'Dépense')], editable=False, max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.CharField(max_length=160)),
                ('method', models.CharField(choices=[('Espèces', 'Espèces'), ('Orange Money', 'Orange Money'), ('MTN MoMo', 'MTN Mobile Money'), ('Virement', 'Virement bancaire'), ('Chèque', 'Chèque')], default='Espèces', max_length=20)),
                ('reference', models.CharField(blank=True, default='', help_text='N° de pièce / facture', max_length=60)),
                ('cancelled', models.BooleanField(default=False)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=120)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(blank=True, help_text="Pour les salaires : l'enseignant payé", null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.personnel')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.transactioncategory')),
            ],
            options={
                'db_table': '"Transaction"',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FeeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(db_index=True, max_length=9)),
                ('amount', models.PositiveIntegerField(help_text='Remise en FCFA')),
                ('reason', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_discounts', to='student.student')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.feetype')),
            ],
            options={
                'db_table': '"FeeDiscount"',
                'unique_together': {('student', 'fee_type', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(db_index=True, max_length=9)),
                ('amount', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('Espèces', 'Espèces'), ('Orange Money', 'Orange Money'), ('MTN MoMo', 'MTN Mobile Money'), ('Virement', 'Virement bancaire'), ('Chèque', 'Chèque')], default='Espèces', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('note', models.CharField(blank=True, default='', max_length=120)),
                ('cancelled', models.BooleanField(default=False)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=120)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.feetype')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='student.student')),
            ],
            options={
                'db_table': '"StudentPayment"',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['school_year', 'fee_type'], name='StudentPaym_school__dffb9a_idx')],
            },
        ),
    ]
