# Generated by Django 5.1.8 on 2026-07-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='salary_month',
            field=models.DateField(blank=True, help_text="Pour les salaires : 1er jour du mois payé. Sert à l'anti-doublon (un salaire par personne et par mois).", null=True),
        ),
    ]
