# Generated by Django 5.1.8 on 2026-07-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_salary_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbox',
            name='default_hourly_rate',
            field=models.PositiveIntegerField(blank=True, help_text="Taux horaire par défaut (FCFA/h). Pré-remplit le taux d'un vacataire horaire quand le sien n'est pas encore configuré. Jamais utilisé pour le calcul : il ne fait que remplir le champ, qui reste modifiable.", null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Salaires HORAIRES : heures payées ce mois (trace + fiche).', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='salary_month',
            field=models.DateField(blank=True, help_text='Salaires : 1er jour du mois payé (anti-doublon).', null=True),
        ),
    ]
