# Generated by Django 5.1.8 on 2026-08-21 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_cashbox_default_hourly_rate_transaction_hours_and_more'),
        ('student', '0013_studentenrollment_discipline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpayment',
            name='student_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='student.student'),
        ),
    ]
