# Generated by Django 5.1.8 on 2026-08-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_studentpayment_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='beneficiary_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
