# Generated by Django 5.1.8 on 2025-04-28 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('matiere', models.CharField(blank=True, max_length=50, null=True)),
                ('groupe', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"Discipline"',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30, null=True)),
                ('contact', models.CharField(max_length=9, unique=True)),
                ('contact1', models.CharField(max_length=9, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('civilite', models.CharField(choices=[('Monsieur', 'Monsieur'), ('Madame', 'Madame')])),
                ('grade', models.CharField(choices=[('PCEG', 'PCEG'), ('PLEG', 'PLEG'), ('PCET', 'PCET'), ('PLET', 'PLET'), ('CO', 'CO'), ('Contractuel', 'Contractuel'), ('Autre', 'Autre')])),
                ('poste', models.CharField(choices=[('Autre', 'Autre'), ('Enseignant', 'Enseignant'), ('Directeur', 'Directeur'), ('Proviseur', 'Proviseur'), ('Principal', 'Principal'), ('Censeur', 'Censeur'), ('Surveillant-Général', 'Surveillant-Général'), ('Intendant', 'Intendant'), ('Économe', 'Économe'), ("Conseiller d'orientation", "Conseiller d'orientation")])),
                ('since', models.IntegerField(max_length=2, null=True)),
                ('photo', models.ImageField(upload_to='image/staff')),
                ('discipline', models.ManyToManyField(to='staff.discipline')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"Personnel"',
            },
        ),
    ]
