# Generated by Django 5.1.8 on 2025-04-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='since',
            field=models.IntegerField(null=True),
        ),
    ]
