# Generated by Django 5.1.8 on 2025-05-14 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_personnel_since'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='poste',
            field=models.CharField(choices=[('Autre', 'Autre'), ('Enseignant', 'Enseignant'), ('Directeur', 'Directeur'), ('Proviseur', 'Proviseur'), ('Principal', 'Principal'), ('Censeur', 'Censeur'), ('Surveillant-Général', 'Surveillant-Général'), ('Surveillant de secteur', 'Surveillant de secteur'), ('Gardien', 'Gardien'), ('Intendant', 'Intendant'), ('Économe', 'Économe'), ("Conseiller d'orientation", "Conseiller d'orientation")]),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_member', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
