# Generated by Django 5.1.8 on 2025-08-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_personnel_poste_alter_personnel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='grade',
            field=models.CharField(choices=[('PCEG', 'PCEG'), ('PLEG', 'PLEG'), ('PCET', 'PCET'), ('PLET', 'PLET'), ('CO', 'CO'), ('Contractuel', 'Contractuel'), ('Autre', 'Autre')], default='Autre'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(null=True, upload_to='image/staff'),
        ),
    ]
