# Generated by Django 5.1.8 on 2025-08-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_personnel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
