# Generated by Django 5.1.8 on 2025-09-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_personnel_unique_notnull_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='poste',
            field=models.CharField(choices=[('Autre', 'Autre'), ('Enseignant', 'Enseignant'), ("Chef d'Établissement", "Chef d'Établissement"), ('Censeur', 'Censeur'), ('Surveillant-Général', 'Surveillant-Général'), ('Surveillant de secteur', 'Surveillant de secteur'), ('Gardien', 'Gardien'), ('Intendant', 'Intendant'), ('Économe', 'Économe'), ("Conseiller d'orientation", "Conseiller d'orientation")]),
        ),
    ]
