# Generated by Django 5.1.8 on 2025-11-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_personnel_poste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('label', models.TextField()),
                ('responsables', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '"Activities"',
                'ordering': ('start', 'end'),
            },
        ),
    ]
