# Generated by Django 5.1.8 on 2025-11-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='responsables',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
