# Generated by Django 5.1.8 on 2025-11-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_alter_activities_responsables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='activities',
            name='start',
            field=models.DateField(),
        ),
    ]
