# Generated by Django 5.1.8 on 2025-12-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_alter_activities_end_alter_activities_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='civilite',
            field=models.CharField(choices=[('Monsieur', 'Monsieur'), ('Madame', 'Madame')], max_length=10),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='grade',
            field=models.CharField(choices=[('PCEG', 'PCEG'), ('PLEG', 'PLEG'), ('PCET', 'PCET'), ('PLET', 'PLET'), ('CO', 'CO'), ('Contractuel', 'Contractuel'), ('Autre', 'Autre')], default='Autre', max_length=30),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/staff'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='poste',
            field=models.CharField(choices=[('Autre', 'Autre'), ('Enseignant', 'Enseignant'), ("Chef d'Établissement", "Chef d'Établissement"), ('Censeur', 'Censeur'), ('Surveillant-Général', 'Surveillant-Général'), ('Surveillant de secteur', 'Surveillant de secteur'), ('Gardien', 'Gardien'), ('Intendant', 'Intendant'), ('Économe', 'Économe'), ("Conseiller d'orientation", "Conseiller d'orientation")], max_length=30),
        ),
    ]
