# Generated by Django 5.1.8 on 2026-06-12 05:39

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_alter_personnel_civilite_alter_personnel_grade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personnel',
            options={'base_manager_name': 'objects_all'},
        ),
        migrations.AlterModelManagers(
            name='personnel',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('objects_all', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='en_poste',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
