# Generated by Django 5.1.8 on 2026-07-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_alter_personnel_options_alter_personnel_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='nb_heures',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Nombre d'heures (informatif, affiché sur la fiche d'émargement). Facultatif.", null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='salaire',
            field=models.PositiveIntegerField(blank=True, help_text="Salaire mensuel (FCFA). Vide -> ne perçoit pas de salaire de l'établissement.", null=True),
        ),
    ]
