# Generated by Django 5.1.8 on 2026-07-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_personnel_nb_heures_personnel_salaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='nb_heures',
        ),
        migrations.AddField(
            model_name='personnel',
            name='default_hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Nombre d'heures mensuel habituel (pré-remplit la paie ; ajustable chaque mois).", null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='hourly_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Taux horaire négocié (FCFA/h). Utilisé si mode = HORAIRE.', null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='salary_mode',
            field=models.CharField(blank=True, choices=[('FIXE', 'Salaire fixe (forfait)'), ('HORAIRE', "À l'heure (taux × heures)")], help_text="Vide = non rémunéré par l'établissement.", max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='salaire',
            field=models.PositiveIntegerField(blank=True, help_text='Salaire mensuel FIXE (FCFA). Utilisé si mode = FIXE.', null=True),
        ),
    ]
