# Generated by Django 5.1.8 on 2026-07-31 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_remove_personnel_nb_heures_personnel_default_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='discipline_formation',
            field=models.CharField(blank=True, default='', help_text='Discipline de formation (ex. Informatique, Mathématiques). Sert (uniquement si poste est Enseignant) à la mention « En qualité de » — distincte des matières effectivement enseignées cette année.', max_length=60),
        ),
        migrations.AddField(
            model_name='personnel',
            name='matricule',
            field=models.CharField(blank=True, default='', help_text='Matricule administratif du membre du personnel.', max_length=10),
        ),
        migrations.AddField(
            model_name='personnel',
            name='note_service_date',
            field=models.DateField(blank=True, help_text='Date de la décision / note de service.', null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='note_service_number',
            field=models.CharField(blank=True, default='', help_text="N° de la décision / note de service / arrêté / d'affectation ou de nomination.", max_length=80),
        ),
        migrations.AddField(
            model_name='personnel',
            name='provenance',
            field=models.CharField(blank=True, default='', help_text='École de formation ou poste précédent (ex. ENS de Yaoundé, Lycée de XXX).', max_length=120),
        ),
    ]
