# Generated by Django 5.1.8 on 2026-08-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_alter_personnel_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='poste',
            field=models.CharField(choices=[('Autre', 'Autre'), ('Enseignant', 'Enseignant'), ("Chef d'Établissement", "Chef d'Établissement"), ('Censeur', 'Censeur'), ('Surveillant Général', 'Surveillant Général'), ("Conseiller d'orientation", "Conseiller d'orientation"), ('Surveillant de secteur', 'Surveillant de secteur'), ('Vigile de jour', 'Vigile de jour'), ('Vigile de nuit', 'Vigile de nuit'), ('Intendant', 'Intendant'), ('Économe', 'Économe'), ('Secrétaire', 'Secrétaire'), ('Bibliothécaire', 'Bibliothécaire'), ('Infirmier', 'Infirmier'), ('Technicien de surface', 'Technicien de surface')], max_length=30),
        ),
    ]
