# Generated by Django 5.1.8 on 2025-04-28 04:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('type_ets', models.CharField(choices=[('Lycée', 'Lycée'), ('CES', 'CES'), ('CES Bilingue', 'CES Bilingue'), ('Lycée Bilingue', 'Lycée Bilingue'), ('CETIC', 'CETIC'), ('Lycée Technique', 'Lycée Technique')], default='CES', verbose_name='Type')),
                ('region', models.CharField(choices=[('DU CENTRE', 'DU CENTRE'), ('DU LITTORAL', 'DU LITTORAL'), ("DE L'OUEST", "DE L'OUEST"), ('DU NORD-OUEST', 'DU NORD-OUEST'), ('DU SUD-OUEST', 'DU SUD-OUEST'), ("DE L'ADAMAOUA", "DE L'ADAMAOUA"), ("DE L'EST", "DE L'EST"), ('DU SUD', 'DU SUD'), ("DE L'EXTRÊME-NORD", "DE L'EXTRÊME-NORD"), ('DE NORD', 'DU NORD')], default="DE L'OUEST", verbose_name='Délégation régionale')),
                ('departement', models.CharField(blank=True, null=True, verbose_name='Délégation départementale')),
                ('rgn', models.CharField(choices=[('CENTRE', 'CENTRE'), ('LITTORAL', 'LITTORAL'), ('WEST', 'WEST'), ('NORTH-WEST', 'NORTH-WEST'), ('SOUTH-WEST', 'SOUTH-WEST'), ('ADAMAOUA', 'ADAMAOUA'), ('EAST', 'EAST'), ('SOUTH', 'SOUTH'), ('FAR-NORTH', 'FAR-NORTH'), ('NORTH', 'NORTH')], default="DE L'OUEST", verbose_name='Regional delegation')),
                ('dptm', models.CharField(blank=True, null=True, verbose_name='Divisional delegation')),
                ('contact', models.CharField(max_length=9, verbose_name='Contact')),
                ('contact1', models.CharField(blank=True, max_length=9, null=True, verbose_name='Contact1')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('pobox', models.CharField(blank=True, max_length=50, verbose_name='Boîte Postale')),
                ('immatriculation', models.CharField(blank=True, max_length=30, verbose_name='N° Immatriculation')),
                ('logo', models.ImageField(blank=True, upload_to='image/', verbose_name='Logo')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('licence', models.BooleanField(default=False, verbose_name='Autorisé')),
            ],
            options={
                'verbose_name': 'Etablissement',
                'verbose_name_plural': 'Etablissements',
                'db_table': '"School"',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrateur')),
                ('civilite', models.CharField(choices=[('Monsieur', 'Monsieur'), ('Madame', 'Madame')], default='Monsieur', verbose_name='Civilité')),
                ('contact', models.CharField(max_length=9, verbose_name='Contact')),
                ('poste', models.CharField(choices=[('Autre', 'Autre'), ('Enseignant', 'Enseignant'), ('Directeur', 'Directeur'), ('Proviseur', 'Proviseur'), ('Principal', 'Principal'), ('Censeur', 'Censeur'), ('Surveillant-Général', 'Surveillant-Général'), ('Intendant', 'Intendant'), ('Économe', 'Économe'), ("Conseiller d'orientation", "Conseiller d'orientation")], default='Autre')),
                ('droits', models.CharField(blank=True, null=True)),
                ('theme', models.CharField(default='blue')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentification.school', verbose_name='Etablissement')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
