# Generated by Django 5.1.8 on 2025-05-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='poste',
            field=models.CharField(choices=[('Autre', 'Autre'), ('Enseignant', 'Enseignant'), ('Directeur', 'Directeur'), ('Proviseur', 'Proviseur'), ('Principal', 'Principal'), ('Censeur', 'Censeur'), ('Surveillant-Général', 'Surveillant-Général'), ('Surveillant de secteur', 'Surveillant de secteur'), ('Gardien', 'Gardien'), ('Intendant', 'Intendant'), ('Économe', 'Économe'), ("Conseiller d'orientation", "Conseiller d'orientation")], default='Autre'),
        ),
    ]
