# Generated by Django 5.1.8 on 2025-08-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_alter_user_poste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='licence',
        ),
        migrations.AddField(
            model_name='school',
            name='with_competences',
            field=models.BooleanField(default=True, verbose_name='Inclure les compétences'),
        ),
    ]
