# Generated by Django 5.1.8 on 2025-08-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_remove_school_licence_school_with_competences'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='licence',
            field=models.DateField(null=True, verbose_name="Autorisé Jusqu'au"),
        ),
    ]
