# Generated by Django 5.1.8 on 2025-08-13 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_school_licence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='school',
            name='licence',
            field=models.DateField(blank=True, null=True, verbose_name="Autorisé Jusqu'au"),
        ),
        migrations.CreateModel(
            name='TrancheHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('fin', models.TimeField()),
                ('is_cours', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches_horaires', to='authentification.school')),
            ],
            options={
                'db_table': '"TrancheHoraire"',
                'ordering': ['start'],
            },
        ),
    ]
