# Generated by Django 5.1.8 on 2025-08-13 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_alter_school_email_alter_school_licence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tranchehoraire',
            old_name='fin',
            new_name='end',
        ),
    ]
