# Generated by Django 5.1.8 on 2025-08-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0007_rename_fin_tranchehoraire_end'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tranchehoraire',
            constraint=models.UniqueConstraint(fields=('school', 'start'), name='unique_school_start'),
        ),
        migrations.AddConstraint(
            model_name='tranchehoraire',
            constraint=models.UniqueConstraint(fields=('school', 'end'), name='unique_school_end'),
        ),
    ]
