# Generated by Django 5.1.8 on 2025-08-13 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0008_tranchehoraire_unique_school_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='day_start',
            field=models.TimeField(default=datetime.time(7, 30)),
        ),
        migrations.AddField(
            model_name='school',
            name='first_break_after',
            field=models.IntegerField(choices=[(2, 2), (3, 3)], default=3),
        ),
        migrations.AddField(
            model_name='school',
            name='nb_plages',
            field=models.IntegerField(choices=[(6, 6), (7, 7), (8, 8), (9, 9)], default=8),
        ),
        migrations.AddField(
            model_name='school',
            name='second_break_after',
            field=models.IntegerField(choices=[(4, 4), (5, 5), (6, 6)], default=5),
        ),
    ]
