# Generated by Django 5.1.8 on 2025-08-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0009_school_day_start_school_first_break_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='plage_duration',
            field=models.IntegerField(choices=[(50, 50), (55, 55), (60, 60)], default=55),
        ),
    ]
