# Generated by Django 5.1.8 on 2025-08-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0010_school_plage_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='first_break_duration',
            field=models.IntegerField(choices=[(10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=15),
        ),
        migrations.AddField(
            model_name='school',
            name='second_break_duration',
            field=models.IntegerField(choices=[(10, 10), (15, 15), (20, 20), (25, 25), (30, 30)], default=30),
        ),
    ]
