# Generated by Django 5.1.8 on 2025-08-13 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0012_tranchehoraire_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tranchehoraire',
            name='unique_school_number',
        ),
        migrations.RemoveField(
            model_name='tranchehoraire',
            name='number',
        ),
    ]
