# Generated by Django 5.1.8 on 2025-08-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0013_remove_tranchehoraire_unique_school_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tranchehoraire',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='tranchehoraire',
            constraint=models.UniqueConstraint(fields=('school', 'number'), name='unique_school_number'),
        ),
    ]
