# Generated by Django 5.1.8 on 2025-08-14 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0014_tranchehoraire_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tranchehoraire',
            name='unique_school_start',
        ),
        migrations.RemoveConstraint(
            model_name='tranchehoraire',
            name='unique_school_end',
        ),
    ]
