# Generated by Django 5.1.8 on 2025-08-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0015_remove_tranchehoraire_unique_school_start_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tranchehoraire',
            options={'ordering': ['number']},
        ),
    ]
