# Generated by Django 5.1.8 on 2025-09-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0016_alter_tranchehoraire_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='mergedprogrammations',
            field=models.BooleanField(default=False, verbose_name='Programmations Combinées'),
        ),
        migrations.AlterField(
            model_name='school',
            name='type_ets',
            field=models.CharField(choices=[('Lycée', 'Lycée'), ('CES', 'CES'), ('CES Bilingue', 'CES Bilingue'), ('Lycée Bilingue', 'Lycée Bilingue'), ('CETIC', 'CETIC'), ('Lycée Technique', 'Lycée Technique'), ('Collège', 'Collège')], default='CES', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='poste',
            field=models.CharField(choices=[('Autre', 'Autre'), ('Enseignant', 'Enseignant'), ("Chef d'Établissement", "Chef d'Établissement"), ('Censeur', 'Censeur'), ('Surveillant-Général', 'Surveillant-Général'), ('Surveillant de secteur', 'Surveillant de secteur'), ('Gardien', 'Gardien'), ('Intendant', 'Intendant'), ('Économe', 'Économe'), ("Conseiller d'orientation", "Conseiller d'orientation")], default='Autre'),
        ),
    ]
