# Generated by Django 5.1.8 on 2025-09-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0017_school_mergedprogrammations_alter_school_type_ets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='localite',
            field=models.CharField(max_length=50, null=True, verbose_name='Localité'),
        ),
    ]
