# Generated by Django 5.1.8 on 2025-09-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0018_school_localite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='localite',
            field=models.CharField(max_length=50, verbose_name='Localité'),
        ),
    ]
