# Generated by Django 5.1.8 on 2025-09-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0019_alter_school_localite'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='motto',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Devise'),
        ),
    ]
