# Generated by Django 5.1.8 on 2025-09-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0020_school_motto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='departement',
            field=models.CharField(max_length=50, verbose_name='Délégation départementale'),
        ),
        migrations.AlterField(
            model_name='school',
            name='dptm',
            field=models.CharField(max_length=50, verbose_name='Divisional delegation'),
        ),
        migrations.AlterField(
            model_name='school',
            name='region',
            field=models.CharField(max_length=50, verbose_name='Délégation régionale'),
        ),
        migrations.AlterField(
            model_name='school',
            name='rgn',
            field=models.CharField(max_length=50, verbose_name='Regional delegation'),
        ),
    ]
