# Generated by Django 5.1.8 on 2025-09-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0021_alter_school_departement_alter_school_dptm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='departement',
            field=models.CharField(default='DÉLÉGATION DÉPARTEMENTALE', max_length=50, verbose_name='Délégation départementale'),
        ),
        migrations.AlterField(
            model_name='school',
            name='dptm',
            field=models.CharField(default='DIVISIONAL DELEGATION', max_length=50, verbose_name='Divisional delegation'),
        ),
        migrations.AlterField(
            model_name='school',
            name='region',
            field=models.CharField(default='DÉLÉGATION RÉGIONALE', max_length=50, verbose_name='Délégation régionale'),
        ),
        migrations.AlterField(
            model_name='school',
            name='rgn',
            field=models.CharField(default='REGIONAL DELEGATION', max_length=50, verbose_name='Regional delegation'),
        ),
    ]
