# Generated by Django 5.1.8 on 2025-09-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0022_alter_school_departement_alter_school_dptm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='licence',
            field=models.DateField(blank=True, default='1998-05-23', verbose_name="Autorisé Jusqu'au"),
        ),
    ]
