# Generated by Django 5.1.8 on 2025-09-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0023_alter_school_licence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='licence',
            field=models.DateField(blank=True, verbose_name="Autorisé Jusqu'au"),
        ),
    ]
