# Generated by Django 5.1.8 on 2025-09-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0025_alter_school_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='image/school/', verbose_name='Logo'),
        ),
    ]
