# Generated by Django 5.1.8 on 2026-06-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0026_alter_school_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=9, unique=True)),
                ('annee_debut', models.IntegerField(unique=True)),
                ('is_current', models.BooleanField(default=False)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('date_cloture', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': '"SchoolYear"',
                'ordering': ['-annee_debut'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='unique_current_school_year')],
            },
        ),
    ]
