# Generated by Django 5.1.8 on 2026-06-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0027_schoolyear'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'ordering': ['-annee_debut'], 'verbose_name': 'Année Scolaire', 'verbose_name_plural': 'Années Scolaires'},
        ),
    ]
