# Generated by Django 5.1.8 on 2026-06-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0028_alter_schoolyear_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='libelle',
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
    ]
