# Generated by Django 5.1.8 on 2026-06-09 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0029_alter_schoolyear_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='last_schoolyear_closed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_closed', to='authentification.schoolyear'),
        ),
    ]
