# Generated by Django 5.1.8 on 2026-06-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0030_school_last_schoolyear_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='cachet',
            field=models.ImageField(blank=True, null=True, upload_to='image/school/', verbose_name='Cachet'),
        ),
    ]
