# Generated by Django 5.1.8 on 2026-06-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0031_school_cachet'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='visa',
            field=models.ImageField(blank=True, null=True, upload_to='image/school/', verbose_name='Visa'),
        ),
    ]
