# Generated by Django 5.1.8 on 2026-07-26 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0032_school_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_financial_user',
            field=models.BooleanField(default=False, help_text='Autorisé à utiliser le module financier.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_super_admin',
            field=models.BooleanField(default=False, help_text='Peut archiver/clôturer une année et désigner les responsables financiers. Est désigné par le chef.'),
        ),
        migrations.AddField(
            model_name='user',
            name='named_financial_user_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='named_financial_user_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_users_named', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='named_super_admin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='named_super_admin_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_admins_named', to=settings.AUTH_USER_MODEL),
        ),
    ]
