# Generated by Django 5.1.8 on 2026-08-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0033_user_is_financial_user_user_is_super_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='school_year',
            field=models.CharField(blank=True, default='', help_text='Année scolaire en cours dans cet établissement.', max_length=9),
        ),
    ]
