# Generated by Django 5.1.8 on 2026-08-08 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0034_school_school_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='school_year',
        ),
    ]
