# Generated by Django 5.1.8 on 2026-08-08 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0035_remove_school_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='schoolyear',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_started', to='authentification.schoolyear'),
        ),
    ]
