# Generated by Django 5.1.8 on 2026-08-08 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0036_school_schoolyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='schoolyear',
            new_name='school_year',
        ),
    ]
