# Generated by Django 5.1.8 on 2026-08-19 16:42

import authentification.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0037_rename_schoolyear_school_school_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_year',
            field=models.ForeignKey(blank=True, default=authentification.models.get_current_school_year, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_started', to='authentification.schoolyear'),
        ),
        migrations.AlterField(
            model_name='user',
            name='poste',
            field=models.CharField(choices=[('Autre', 'Autre'), ('Enseignant', 'Enseignant'), ("Chef d'Établissement", "Chef d'Établissement"), ('Censeur', 'Censeur'), ('Surveillant général', 'Surveillant Général'), ("Conseiller d'orientation", "Conseiller d'orientation"), ('Surveillant de secteur', 'Surveillant de secteur'), ('Vigile de jour', 'Vigile de jour'), ('Vigile de nuit', 'Vigile de nuit'), ('Intendant', 'Intendant'), ('Économe', 'Économe'), ('Secrétaire', 'Secrétaire'), ('Bibliothécaire', 'Bibliothécaire'), ('Infirmier', 'Infirmier'), ('Technicien de surface', 'Technicien de surface')], default='Autre'),
        ),
    ]
