# Generated by Django 5.1.8 on 2026-08-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0039_alter_user_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='poste',
            field=models.CharField(choices=[('Autre', 'Autre'), ('Enseignant', 'Enseignant'), ("Chef d'Établissement", "Chef d'Établissement"), ('Censeur', 'Censeur'), ('Surveillant Général', 'Surveillant Général'), ('Chargé des études', 'Chargé des études'), ("Conseiller d'orientation", "Conseiller d'orientation"), ('Surveillant de secteur', 'Surveillant de secteur'), ('Vigile de jour', 'Vigile de jour'), ('Vigile de nuit', 'Vigile de nuit'), ('Intendant', 'Intendant'), ('Économe', 'Économe'), ('Secrétaire', 'Secrétaire'), ('Bibliothécaire', 'Bibliothécaire'), ('Infirmier', 'Infirmier'), ('Technicien de surface', 'Technicien de surface')], default='Autre'),
        ),
    ]
