# Generated by Django 5.1.8 on 2026-08-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0040_alter_user_poste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='type_ets',
            field=models.CharField(choices=[('Lycée', 'Lycée'), ('GHS', 'GHS'), ('CES', 'CES'), ('GSS', 'GSS'), ('CES Bilingue', 'CES Bilingue'), ('Lycée Bilingue', 'Lycée Bilingue'), ('CETIC', 'CETIC'), ('CETIC Bilingue', 'CETIC Bilingue'), ('Lycée Technique', 'Lycée Technique'), ('Lycée Technique Bilingue', 'Lycée Technique Bilingue'), ('Collège', 'Collège'), ('College', 'College'), ('Collège Bilingue', 'Collège Bilingue'), ('Collège Polyvalent', 'Collège Polyvalent')], default='CES', verbose_name='Type'),
        ),
    ]
