# Generated by Django 5.1.8 on 2026-09-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0042_alter_school_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='licence',
            field=models.DateField(verbose_name="Autorisé Jusqu'au"),
        ),
    ]
