# Generated by Django 5.1.8 on 2025-04-28 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evalx', models.IntegerField()),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': '"Period"',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval', models.IntegerField()),
                ('competences', models.TextField()),
                ('note', models.DecimalField(decimal_places=2, default=-1, max_digits=4)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('enseignement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.enseignements')),
            ],
            options={
                'db_table': '"Note"',
            },
        ),
    ]
