# Generated by Django 5.1.8 on 2025-04-28 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('niveau', models.CharField(max_length=15)),
                ('serie', models.CharField(blank=True, max_length=10, null=True)),
                ('dfn', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': '"Class"',
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('lv2', models.CharField(choices=[('Allemand', 'Allemand'), ('Espagnol', 'Espagnol'), ('Chinois', 'Russe'), ('Arabe', 'Arabe')], null=True)),
                ('lv3', models.CharField(choices=[('Russe', 'Russe'), ('Italien', 'Italien')], null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.class')),
                ('titulaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.personnel')),
            ],
            options={
                'db_table': '"ClassRoom"',
            },
        ),
        migrations.CreateModel(
            name='Matieres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeff', models.IntegerField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.class')),
                ('sujet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.discipline')),
            ],
            options={
                'db_table': '"Matieres"',
            },
        ),
        migrations.CreateModel(
            name='Enseignements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignant', to='staff.personnel')),
                ('rapporteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapporteur', to='staff.personnel')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.matieres')),
            ],
            options={
                'db_table': '"Enseignements"',
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='matieres',
            field=models.ManyToManyField(through='classroom.Enseignements', to='classroom.matieres'),
        ),
        migrations.AddField(
            model_name='class',
            name='disciplines',
            field=models.ManyToManyField(blank=True, through='classroom.Matieres', to='staff.discipline'),
        ),
    ]
