# Generated by Django 5.1.8 on 2025-08-13 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_alter_school_email_alter_school_licence_and_more'),
        ('classroom', '0001_initial'),
        ('staff', '0003_alter_personnel_poste_alter_personnel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi')])),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programmations', to='staff.personnel')),
                ('enseignement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.enseignements')),
                ('tranche_horaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.tranchehoraire')),
            ],
            options={
                'db_table': '"Programmation"',
                'constraints': [models.UniqueConstraint(fields=('jour', 'tranche_horaire', 'enseignement'), name='unique_enseignement_jour_tranche'), models.UniqueConstraint(fields=('jour', 'tranche_horaire', 'enseignant'), name='unique_enseignant_jour_tranche')],
            },
        ),
    ]
