# Generated by Django 5.1.8 on 2025-08-19 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0016_alter_tranchehoraire_options'),
        ('classroom', '0002_programmation'),
        ('staff', '0007_personnel_unique_notnull_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='programmation',
            name='unique_enseignement_jour_tranche',
        ),
        migrations.RemoveField(
            model_name='programmation',
            name='enseignement',
        ),
        migrations.AddField(
            model_name='programmation',
            name='matiere',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='classroom.matieres'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='programmation',
            constraint=models.UniqueConstraint(fields=('jour', 'tranche_horaire', 'matiere'), name='unique_matiere_jour_tranche'),
        ),
    ]
