# Generated by Django 5.1.8 on 2025-08-19 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0016_alter_tranchehoraire_options'),
        ('classroom', '0003_remove_programmation_unique_enseignement_jour_tranche_and_more'),
        ('staff', '0007_personnel_unique_notnull_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='programmation',
            name='unique_matiere_jour_tranche',
        ),
        migrations.AddField(
            model_name='programmation',
            name='classroom',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='programmations', to='classroom.classroom'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='programmation',
            constraint=models.UniqueConstraint(fields=('jour', 'tranche_horaire', 'matiere', 'classroom'), name='unique_matiere_classroom_jour_tranche'),
        ),
    ]
