# Generated by Django 5.1.8 on 2025-08-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_remove_programmation_unique_matiere_jour_tranche_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmation',
            name='jour',
            field=models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi')]),
        ),
    ]
