# Generated by Django 5.1.8 on 2025-08-23 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_alter_programmation_jour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmation',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmations', to='classroom.matieres'),
        ),
    ]
