# Generated by Django 5.1.8 on 2025-09-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_alter_programmation_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmation',
            name='classrooms',
            field=models.ManyToManyField(related_name='mergedprogrammations', to='classroom.classroom'),
        ),
    ]
