# Generated by Django 5.1.8 on 2025-09-06 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_programmation_classrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmation',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programmations', to='classroom.classroom'),
        ),
    ]
