# Generated by Django 5.1.8 on 2025-12-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_alter_programmation_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignements',
            name='nlfp1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enseignements',
            name='nlfp2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enseignements',
            name='nlfp3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enseignements',
            name='nlft1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enseignements',
            name='nlft2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enseignements',
            name='nlft3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enseignements',
            name='nlpp1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enseignements',
            name='nlpp2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enseignements',
            name='nlpp3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enseignements',
            name='nlpt1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enseignements',
            name='nlpt2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enseignements',
            name='nlpt3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='lv2',
            field=models.CharField(choices=[('Allemand', 'Allemand'), ('Espagnol', 'Espagnol'), ('Chinois', 'Russe'), ('Arabe', 'Arabe')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='lv3',
            field=models.CharField(choices=[('Russe', 'Russe'), ('Italien', 'Italien')], max_length=15, null=True),
        ),
    ]
