# Generated by Django 5.1.8 on 2025-12-28 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_enseignements_nlfp1_enseignements_nlfp2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignements',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignement', to='classroom.classroom'),
        ),
    ]
