# Generated by Django 5.1.8 on 2026-06-07 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_alter_enseignements_classroom'),
        ('staff', '0012_alter_personnel_civilite_alter_personnel_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='titulaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulaire', to='staff.personnel'),
        ),
    ]
