# Generated by Django 5.1.8 on 2026-08-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_alter_classroom_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='moyenne_min_admission',
            field=models.DecimalField(decimal_places=2, default=10, help_text="Moyenne minimale d'admission (défaut : 10).", max_digits=4),
        ),
        migrations.AddField(
            model_name='classroom',
            name='notes_updated_t1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='notes_updated_t2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='notes_updated_t3',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
