# Generated by Django 5.1.8 on 2026-08-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_classroom_moyenne_min_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='decisions_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
