# Generated by Django 5.1.8 on 2026-08-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_classroom_decisions_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subsystem',
            field=models.CharField(choices=[('ESG-FR', 'ESG-FR'), ('ESG-EN', 'ESG-EN'), ('EST-FR', 'EST-FR'), ('EST-EN', 'EST-EN')], default='ESG-FR', max_length=10),
        ),
    ]
