# Generated by Django 5.1.8 on 2026-08-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0015_class_subsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='lv2',
            field=models.CharField(choices=[('Allemand', 'Allemand'), ('Espagnol', 'Espagnol'), ('Chinois', 'Chinois'), ('Arabe', 'Arabe')], max_length=15, null=True),
        ),
    ]
