# Generated by Django 5.1.8 on 2025-04-28 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=30, null=True, unique=True)),
                ('contact', models.CharField(max_length=9, unique=True)),
                ('profession', models.CharField(max_length=50, null=True)),
                ('civilite', models.CharField(choices=[('Monsieur', 'Monsieur'), ('Madame', 'Madame')])),
            ],
            options={
                'db_table': '"Parent"',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30, null=True)),
                ('statut', models.CharField(choices=[('Nouveau', 'Nouveau'), ('Redoublant', 'Redoublant')])),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('Fille', 'Fille'), ('Garçon', 'Garçon')])),
                ('photo', models.ImageField(upload_to='image/student')),
                ('unique_id', models.IntegerField(unique=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classroom.classroom')),
                ('mere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_children', to='student.parent')),
                ('pere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_children', to='student.parent')),
            ],
            options={
                'db_table': '"Student"',
            },
        ),
        migrations.CreateModel(
            name='StudentDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trim', models.IntegerField(default=1)),
                ('avert', models.BooleanField(default=False)),
                ('excl_def', models.BooleanField(default=False)),
                ('blame', models.BooleanField(default=False)),
                ('cons', models.IntegerField(default=0)),
                ('abs', models.IntegerField(default=0)),
                ('absj', models.IntegerField(default=0)),
                ('retards', models.IntegerField(default=0)),
                ('excl', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline', to='student.student')),
            ],
            options={
                'db_table': 'StudentDiscipline',
            },
        ),
    ]
