# Generated by Django 5.1.8 on 2025-06-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='parent',
            constraint=models.UniqueConstraint(condition=models.Q(('email', None), _negated=True), fields=('email',), name='unique_email_si_non_null'),
        ),
    ]
