# Generated by Django 5.1.8 on 2025-06-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_parent_email_parent_unique_email_si_non_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(max_length=30, null=True, unique=True),
        ),
    ]
