# Generated by Django 5.1.8 on 2025-06-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_parent_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parent',
            name='unique_email_si_non_null',
        ),
        migrations.AddConstraint(
            model_name='parent',
            constraint=models.UniqueConstraint(condition=models.Q(('email', None), _negated=True), fields=('email',), name='unique_courriel_si_non_null'),
        ),
    ]
