# Generated by Django 5.1.8 on 2025-12-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_parent_unique_email_si_non_null_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='civilite',
            field=models.CharField(choices=[('Monsieur', 'Monsieur'), ('Madame', 'Madame')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='statut',
            field=models.CharField(choices=[('Nouveau', 'Nouveau'), ('Redoublant', 'Redoublant')], max_length=15),
        ),
    ]
