# Generated by Django 5.1.8 on 2026-06-06 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0027_schoolyear'),
        ('classroom', '0010_alter_enseignements_classroom'),
        ('student', '0006_alter_parent_civilite_alter_student_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('En cours', 'Année en cours'), ('Promu', 'Promu (classe supérieure)'), ('Redoublant', 'Redoublant'), ('Transféré', 'Transféré (autre établissement)'), ('Sorti', 'A terminé son cursus ou est exclu')], default='En cours', max_length=15)),
                ('moyenne_t1', models.FloatField(blank=True, null=True)),
                ('rang_t1', models.IntegerField(blank=True, null=True)),
                ('moyenne_t2', models.FloatField(blank=True, null=True)),
                ('rang_t2', models.IntegerField(blank=True, null=True)),
                ('moyenne_t3', models.FloatField(blank=True, null=True)),
                ('rang_t3', models.IntegerField(blank=True, null=True)),
                ('moyenne_annuelle', models.FloatField(blank=True, null=True)),
                ('rang_annuel', models.IntegerField(blank=True, null=True)),
                ('decided_by', models.CharField(blank=True, max_length=80, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='classroom.classroom')),
                ('next_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='future_enrollments', to='classroom.classroom')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='authentification.schoolyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='student.student')),
            ],
            options={
                'db_table': '"StudentEnrollment"',
                'ordering': ['-school_year__annee_debut'],
                'constraints': [models.UniqueConstraint(fields=('student', 'school_year'), name='unique_enrollment_per_year')],
            },
        ),
    ]
