# Generated by Django 5.1.8 on 2026-06-09 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_seed_current_enrollments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='decision',
            field=models.CharField(choices=[('En cours', 'Année en cours'), ('Promu', 'Promu (classe supérieure)'), ('Redoublant', 'Redoublant'), ('Transféré', 'Transféré (autre établissement)'), ('Sorti', 'A terminé son cursus ou est exclu'), ('Non statué', 'Décision non saisie')], default='En cours', max_length=15),
        ),
    ]
