# Generated by Django 5.1.8 on 2026-06-10 04:35

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_studentenrollment_decision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'base_manager_name': 'objects_all'},
        ),
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('objects_all', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
