# Generated by Django 5.1.8 on 2026-07-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_student_options_alter_student_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='decision',
            field=models.CharField(choices=[('En cours', 'Année en cours'), ('Promu', 'Promu (classe supérieure)'), ('Redoublant', 'Redoublant'), ('Transféré', 'Transféré (autre établissement)'), ('Sorti', 'A terminé son cursus'), ('Exclu', 'Exclu'), ('Non statué', 'Décision non saisie')], default='En cours', max_length=15),
        ),
    ]
