# Generated by Django 5.1.8 on 2026-08-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_studentenrollment_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='rang_annuel',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='rang_t1',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='rang_t2',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='rang_t3',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
