# Generated by Django 5.1.8 on 2026-08-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_studentenrollment_rang_annuel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='discipline',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='discipline_t1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='discipline_t2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='discipline_t3',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
