# Generated by Django 5.1.8 on 2026-09-02 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_studentenrollment_discipline_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE "Parent" DROP CONSTRAINT IF EXISTS "Parent_email_5bb5e82b_uniq" CASCADE;
            ALTER TABLE "Parent" DROP CONSTRAINT IF EXISTS "unique_courriel_si_non_null" CASCADE;
            ALTER TABLE "Parent" DROP CONSTRAINT IF EXISTS "unique_email_si_non_null" CASCADE;
            ALTER TABLE "Parent" DROP CONSTRAINT IF EXISTS "Parent_email_key" CASCADE;

            DROP INDEX IF EXISTS "Parent_email_5bb5e82b_uniq" CASCADE;
            DROP INDEX IF EXISTS "unique_courriel_si_non_null" CASCADE;
            DROP INDEX IF EXISTS "unique_email_si_non_null" CASCADE;
            DROP INDEX IF EXISTS "Parent_email_key" CASCADE;
            """,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
