# Generated by Django 5.1.8 on 2026-09-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20260902_0117'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parent',
            name='unique_courriel_si_non_null',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='email',
        ),
        migrations.AddField(
            model_name='parent',
            name='courriel',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AddConstraint(
            model_name='parent',
            constraint=models.UniqueConstraint(condition=models.Q(('courriel__gt', ''), ('courriel__isnull', False)), fields=('courriel',), name='unique_courriel_si_non_null'),
        ),
    ]
