# Generated by Django 5.1.8 on 2026-09-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_remove_parent_unique_courriel_si_non_null_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sexe',
            field=models.CharField(choices=[('Fille', 'Féminin'), ('Garçon', 'Masculin')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='unique_id',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.RunSQL(
            sql='ALTER TABLE "Student" ALTER COLUMN "unique_id" TYPE varchar(15) USING "unique_id"::varchar;',
            reverse_sql='ALTER TABLE "Student" ALTER COLUMN "unique_id" TYPE integer USING "unique_id"::integer;',
        ),
    ]
