# Generated by Django 5.1.8 on 2026-09-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_alter_student_sexe_alter_student_unique_id'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE "Student" DROP CONSTRAINT IF EXISTS "Student_unique_id_key" CASCADE;
                
                DROP INDEX IF EXISTS "Student_unique_id_key" CASCADE;
                """,
            reverse_sql=migrations.RunSQL.noop,
        )
    ]
